language: go
dist: xenial
go:
- 1.12
env:
- GO111MODULE=on
install:
- go mod download
script:
- go test -race -coverprofile=coverage.txt -covermode=atomic ./app/...
after_success:
- bash <(curl -s https://codecov.io/bash)
deploy:
- provider: gae
  project: crucial-alpha-706
  promote: false
  on:
    all_branches: true
  edge: true
- provider: gae
  project: crucial-alpha-706
  version: prod
  edge: true
notifications:
  email: false
before_install:
- openssl aes-256-cbc -K $encrypted_16c043351149_key -iv $encrypted_16c043351149_iv
  -in service-account.json.enc -out service-account.json -d
