language: go
sudo: false

go:
  - 1.4

# Notes: http://orcaman.blogspot.com/2014/09/ci-when-githubtravis-meet-gogae.html
install: ./script/ci/install.sh
before_script: ./script/ci/before_script.sh
script: ./script/ci/script.sh
after_success: ./script/ci/after_success.sh

notifications:
  email: false
