language: go
sudo: false

go:
  - 1.4

install:
  - export VERSION=$(curl https://appengine.google.com/api/updatecheck | grep release | grep -o '[0-9\.]*')
  - echo $VERSION
  - export FILE=go_appengine_sdk_linux_amd64-$VERSION.zip
  - echo $FILE
  - curl -O https://storage.googleapis.com/appengine-sdks/featured/$FILE
  - unzip -q $FILE
  # - export HERE=`pwd`
  # - cd $GOROOT/src && GOOS=linux GOARCH=amd64 ./make.bash --no-clean
  # - export GOROOT=$HERE/go_appengine/goroot
  # - go get github.com/mjibson/appstats

script:
  - go version
  - ./go_appengine/goapp test ./app/...
  - ./go_appengine/goapp build ./app/...
