application: crucial-alpha-706
version: 2
runtime: go
api_version: go1

handlers:
- url: /static
  static_dir: static

- url: /
  static_files: static/index.html
  upload: static/index.html

- url: /(favicon\.ico|index\.html)
  static_files: static/\1
  upload: static/(favicon\.ico|index\.html)

- url: /cron/.*
  script: _go_app
  login: admin

- url: /.*
  script: _go_app

error_handlers:
  - file: static/err/default.html
  - error_code: over_quota
    file: static/err/over_quota.html
