application: crucial-alpha-706
version: 1
runtime: python27
api_version: 1
threadsafe: yes

libraries:
- name: lxml
  version: "2.3.5"

handlers:
- url: /static
  static_dir: static

- url: /
  static_files: static/index.html
  upload: static/index.html

- url: /cron/.*
  script: app.cron
  login: admin

- url: /api/.*
  script: app.api

- url: .*
  script: app.err

error_handlers:
  - file: err/default.html
