name: 'gcloud auth'
description: 'Sign into Google Cloud'
runs:
  using: composite
  steps:

    # copy/pasta: https://github.com/google-github-actions/setup-gcloud#service-account-key-json 
    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'
    - name: 'Use gcloud CLI'
      run: 'gcloud info'