name: Release
on:
  push:
    branches:
    - master
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
      - name: Deploy to staging
        id: deploy
        env:
          PROJECT: crucial-alpha-706
        run: gcloud app deploy --version prod --project $PROJECT --quiet
