name: Release
on:
  pull_request:
    types: [closed]
jobs:
  deploy:
    if: github.event.pull_request.merged == true
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
      - name: Deploy to staging
        id: deploy
        env:
          PROJECT: crucial-alpha-706
          VERSION: ${{ github.event.pull_request.number }}
        run: gcloud app versions migrate pr-$VERSION --project $PROJECT --quiet
