name: Release
on:
  pull_request:
    types: [closed]
# jobs:
#   merge-PR:
#     # if: github.event.pull_request.merged == true
#     runs-on: ubuntu-latest
#     steps:
#       - name: Dump GitHub context
#         env:
#           GITHUB_CONTEXT: ${{ toJson(github) }}
#         run: echo "$GITHUB_CONTEXT"
jobs:
  deploy:
    # if: github.event.pull_request.merged == true
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
      - name: Deploy to staging
        id: deploy
        env:
          PROJECT: crucial-alpha-706
          VERSION: ${{ github.event.pull_request.number }}
        run: gcloud app deploy --project $PROJECT --version pr-$VERSION --quiet
