name: Release
on:
  pull_request:
    types: [closed]
jobs:
  deploy:
    if: github.event.pull_request.merged == true
    name: Deploy
    runs-on: ubuntu-latest
    steps:

      # copy/pasta: https://github.com/google-github-actions/setup-gcloud#service-account-key-json 
      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      - name: Deploy to staging
        id: deploy
        env:
          PROJECT: crucial-alpha-706
          VERSION: ${{ github.event.pull_request.number }}
        run: gcloud app versions migrate pr-$VERSION --project $PROJECT --quiet
