name: Release
on:
  pull_request:
    types: [closed]
jobs:
  deploy:
    if: github.event.pull_request.merged == true
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/gcloud
      - name: Deploy to staging
        id: deploy
        env:
          PROJECT: crucial-alpha-706
          VERSION: ${{ github.event.pull_request.number }}
        run: gcloud app versions migrate pr-$VERSION --project $PROJECT --quiet
