name: PR
on: pull_request
jobs:
  pr:
    name: CD
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: crucial-alpha-706
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Use gcloud CLI
        run: gcloud info
      - name: Deploy to staging
        id: deploy
        env:
          VERSION: ${{ github.event.pull_request.number }}
          PROJECT: crucial-alpha-706
        run: |
          gcloud app deploy --version pr-$VERSION --project $PROJECT --no-promote --quiet
          RES=`gcloud app browse --project=$PROJECT --version=pr-$VERSION 2>&1 | tail -n 1`
          echo "::set-output name=url::$RES"

      # See: https://octokit.github.io/rest.js/
      - uses: actions/github-script@0.4.0
        env:
          ADDRESS: ${{ steps.deploy.outputs.url }}
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const body = 'Deployed to ' + process.env.ADDRESS + ' for manual testing.'
            console.log(body, context)

            const opts = github.issues.listComments.endpoint.merge({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo
            })
            const comments = await github.paginate(opts)

            // Try to find/update an existing comment
            for (const comment of comments) {
              if (comment.body.startsWith('Deployed to ')) {
                await github.issues.updateComment({
                  comment_id: comment.id,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  body: body + '\n\nUpdated with: ' + context.payload.after,
                })
                return;
              }
            }

            // Create a new one
            await github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body,
            })
